image: "python:3"

test:
  script:
    - rm -f .coverage* && pip3 install coverage && python3 -m coverage run --parallel ./setup.py test && python3 -m coverage combine && python3 -m coverage report --include=aiocoap/\*
